"""Documentation & Metadata Agent — LLM writes README + column descriptions."""
from __future__ import annotations

from .base import Agent, RunContext
from .. import llm


SYSTEM_PROMPT = """You are the Documentation & Metadata Agent.
Write a concise README.md for a newly onboarded enterprise data product.
Include: overview, ownership, SLA, downstream consumers, runbook, and any
governance notes (PII, masking, retention). Use markdown, no HTML.
Return the README as plain markdown, without any code fences around the whole doc."""


class DocsAgent(Agent):
    id = "docs"
    name = "Documentation & Lineage Agent"
    stage = "docs"

    async def run(self, ctx: RunContext) -> dict:
        self.started(ctx)
        req = ctx.request
        pii_summary = ctx.outputs.get("pii", {}).get("by_class", {})

        self.emit(ctx, "Requesting README from LLM…")
        prompt = (
            f"Source name: {req['source_name']}\n"
            f"Type: {req['source_type']}\n"
            f"Refresh: {req['refresh']}\n"
            f"Business owner: {req.get('business_owner','Customer Operations COE')}\n"
            f"Steward: shanmugapriya.kandasamy@cognizant.com\n"
            "Downstream consumers: Power BI 'Customer 360 — Certified', "
            "reverse-ETL 'billing_alerts_v2'.\n"
            f"PII summary: {pii_summary}\n"
            "Keep the README ~40-60 lines."
        )
        readme = llm.complete(SYSTEM_PROMPT, prompt, temperature=0.3, max_tokens=1200)
        if not readme:
            readme = _fallback_readme(req)

        p1 = ctx.write_text(("docs", "README.md"), readme)
        self.artifact(ctx, "README.md", p1, preview=readme)

        exposure = _render_exposure_yml()
        p2 = ctx.write_text(("docs", "exposures.yml"), exposure)
        self.artifact(ctx, "exposures.yml", p2, preview=exposure)

        lineage = _render_lineage()
        p3 = ctx.write_json(("docs", "lineage.json"), lineage)
        self.artifact(ctx, "lineage.json", p3, preview="")

        decision = await self.wait_for_approval(
            ctx, "biz_validation",
            title="Business validation (optional)",
            body="Confirm the lineage and governance objects reflect business intent. "
                 "This is an optional review — click Skip if not applicable to this "
                 "onboarding, or Approve to lock them in.",
            optional=True,
            preview={"kind": "lineage-preview",
                     "nodes": len(lineage["nodes"]),
                     "edges": len(lineage["edges"]),
                     "readme_bytes": len(readme)},
        )
        if not decision["approved"]:
            raise RuntimeError("Business validation rejected.")

        ctx.outputs["docs"] = {
            "readme_bytes": len(readme),
            "lineage_nodes": len(lineage["nodes"]),
            "biz_validation_skipped": decision["skipped"],
        }
        outcome = "skipped" if decision["skipped"] else "confirmed by business"
        self.done(ctx, f"README, catalog entry, and lineage graph published · biz validation {outcome}")
        return ctx.outputs["docs"]


def _fallback_readme(req: dict) -> str:
    return f"""# {req['source_name']} — Enterprise Data Platform

Auto-generated by the Cognizant Documentation & Metadata Agent.

## Overview
Ingests {req['source_name']} ({req['source_type']}) every {req['refresh']}.
Data lands in `DP_RAW.RAW_CCB`, transformed by dbt to staging and mart
layers, and exposed to Power BI as a certified customer-360 dataset.

## Ownership
- Business owner: **{req.get('business_owner','Customer Operations COE')}**
- Technical owner: **Data Platform team**
- Steward: shanmugapriya.kandasamy@cognizant.com

## SLA
- Refresh: every {req['refresh']}
- Lag alert: > 15 minutes
- DQ blocker rules must be green for run publication

## Downstream consumers
- Power BI · *Customer 360 — Certified*
- Reverse-ETL job `billing_alerts_v2` (Hightouch)

## Runbook
1. On freshness alert, inspect `DP_META.SOURCE_FRESHNESS` (source='ORACLE_CCB').
2. On DQ failure, review `DP_META.DQ_RESULTS`, filter `domain='customer_billing'`.
3. Escalation: `#customer-ops-oncall`, then customer_ops_coe@coned.com.
"""


def _render_exposure_yml() -> str:
    return """# dbt/models/ccb/exposures.yml
version: 2
exposures:
  - name: powerbi_customer_360_certified
    label: "Customer 360 — Certified"
    type: dashboard
    maturity: high
    url: https://app.powerbi.com/groups/...
    owner: {name: Customer Operations COE, email: customer_ops_coe@coned.com}
    depends_on: [ref('dim_customer_360'), ref('dim_meter'), ref('fct_bill'), ref('fct_payment')]
"""


def _render_lineage() -> dict:
    return {
        "nodes": [
            {"id": "src",   "label": "Oracle CC&B",         "type": "source"},
            {"id": "raw_pe","label": "RAW.PERSON",           "type": "raw"},
            {"id": "raw_ac","label": "RAW.ACCOUNT",          "type": "raw"},
            {"id": "raw_pr","label": "RAW.PREMISE",          "type": "raw"},
            {"id": "raw_sa","label": "RAW.SERVICE_AGREEMENT","type": "raw"},
            {"id": "raw_mt","label": "RAW.METER",            "type": "raw"},
            {"id": "raw_bl","label": "RAW.BILL",             "type": "raw"},
            {"id": "raw_py","label": "RAW.PAYMENT",          "type": "raw"},
            {"id": "raw_cc","label": "RAW.CUSTOMER_CONTACT", "type": "raw"},
            {"id": "stg_pe","label": "stg_ccb__person",      "type": "staging"},
            {"id": "stg_ac","label": "stg_ccb__account",     "type": "staging"},
            {"id": "stg_pr","label": "stg_ccb__premise",     "type": "staging"},
            {"id": "stg_sa","label": "stg_ccb__service_agreement","type": "staging"},
            {"id": "stg_mt","label": "stg_ccb__meter",       "type": "staging"},
            {"id": "stg_bl","label": "stg_ccb__bill",        "type": "staging"},
            {"id": "stg_py","label": "stg_ccb__payment",     "type": "staging"},
            {"id": "stg_cc","label": "stg_ccb__customer_contact","type": "staging"},
            {"id": "dim_c", "label": "dim_customer_360",     "type": "mart"},
            {"id": "dim_m", "label": "dim_meter",            "type": "mart"},
            {"id": "fct_b", "label": "fct_bill",             "type": "mart"},
            {"id": "fct_p", "label": "fct_payment",          "type": "mart"},
            {"id": "pbi",   "label": "Power BI",             "type": "bi"},
        ],
        "edges": [
            ["src","raw_pe"], ["src","raw_ac"], ["src","raw_pr"], ["src","raw_sa"],
            ["src","raw_mt"], ["src","raw_bl"], ["src","raw_py"], ["src","raw_cc"],
            ["raw_pe","stg_pe"], ["raw_ac","stg_ac"], ["raw_pr","stg_pr"],
            ["raw_sa","stg_sa"], ["raw_mt","stg_mt"], ["raw_bl","stg_bl"],
            ["raw_py","stg_py"], ["raw_cc","stg_cc"],
            ["stg_pe","dim_c"], ["stg_ac","dim_c"], ["stg_pr","dim_c"],
            ["stg_sa","dim_m"], ["stg_mt","dim_m"],
            ["stg_bl","fct_b"], ["stg_ac","fct_b"],
            ["stg_py","fct_p"], ["stg_bl","fct_p"],
            ["dim_c","pbi"], ["dim_m","pbi"], ["fct_b","pbi"], ["fct_p","pbi"],
        ],
    }
